// Bounded native-component operations. Load, then invoke one named stage per call.
// The JSON is injected by tools/design-guide.mjs; no credentials enter this file.
if(penpot.currentFile.id!=='24d9d841-759d-81bc-8008-b518bc70d8b3')throw Error('OpenSP only');
const lib=penpot.library.local;
const d=storage.guide={article:__ARTICLE__,colors:Object.fromEntries(lib.colors.map(c=>[c.name,c])),type:Object.fromEntries(lib.typographies.map(t=>[t.name,t])),c:Object.fromEntries(lib.components.map(c=>[c.name,c]))};
for(const s of d.article.sections)if(d.c[s.id])d.c['Section / '+s.id]=d.c[s.id];
d.find=(r,n)=>{const s=penpotUtils.findShape(s=>s.name===n||s.name.split('/').at(-1).trim()===n,r);if(!s)throw Error('Missing '+n);return s;};
d.visible=r=>penpotUtils.findShapes(s=>{let p=s;while(p&&p.id!==r.id){if(p.hidden||p.name.startsWith('Archive'))return false;p=p.parent;}return s.id!==r.id;},r);
d.put=(s,p,x,y,w,h)=>{if(p)s.parent?.id!==p.id&&p.appendChild(s);if(w!==undefined)s.resize(w,h);s.x=(p?.x||0)+x;s.y=(p?.y||0)+y;return s;};
d.board=(n,x,y,w,h,fill=null)=>{const b=penpot.createBoard();b.name=n;b.resize(w,h);b.x=x;b.y=y;b.fills=fill?[d.colors[fill].asFill()]:[];return b;};
d.rect=(p,n,x,y,w,h,fill='Line')=>{const s=penpot.createRectangle();s.name=n;s.fills=[d.colors[fill].asFill()];s.strokes=[];return d.put(s,p,x,y,w,h);};
d.txt=(p,n,value,x,y,w,h,style='Body',color='Ink')=>{const s=penpot.createText(value);s.name=n;s.applyTypography(d.type[style]);s.lineHeight=d.type[style].lineHeight;s.growType='fixed';s.fills=[d.colors[color].asFill()];return d.put(s,p,x,y,w,h);};
d.inst=(n,p,x,y,label=n)=>{const s=d.c[n].instance();s.name=label;return d.put(s,p,x,y);};
d.make=(n,x,y,w,h,draw)=>{if(d.c[n])return d.c[n].id;const b=d.board(n,x,y,w,h);draw(b);const c=lib.createComponent([b]);c.name=n;c.path='OpenSP / Guide';d.c[n]=c;return c.id;};
d.height=(str,w,size=20,leading=1.6)=>{const cap=Math.floor(w/(size*.51));let lines=0;for(const para of str.split('\n')){let line=0;for(const word of para.split(' ')){if(line&&line+word.length+1>cap){lines++;line=word.length;}else line+=(line?1:0)+word.length;}lines++;}return Math.ceil(lines*size*leading)+4;};
d.textFit=(s,w,style='Body')=>{s.applyTypography(d.type[style]);s.lineHeight=d.type[style].lineHeight;s.resize(w,d.height(s.characters,w,Number(d.type[style].fontSize),Number(d.type[style].lineHeight)));};
d.prepare=()=>{
 if(penpot.currentPage.name!=='Guide components')throw Error('Open Guide components');
 for(const [name,size,font,leading] of [['Article title',60,'Arimo',1.08],['Code',14,'Cousine',1.65]])if(!d.type[name]){const t=lib.createTypography();t.name=name;t.path='OpenSP / Guide';const f=penpot.fonts.all.find(f=>f.name===font);t.setFont(f,f.variants.find(v=>v.fontWeight==='400'&&v.fontStyle==='normal'));t.fontSize=String(size);t.lineHeight=String(leading);t.letterSpacing=name==='Article title'?'-1.5':'0';d.type[name]=t;}
 d.make('Article paragraph',0,0,760,120,b=>d.txt(b,'Paragraph','Shared article reading text.',0,0,760,120));
 d.make('Article heading',0,180,992,64,b=>{d.txt(b,'Heading','Section heading',0,0,950,44,'Heading');});
 d.make('Figure caption',0,300,992,52,b=>d.txt(b,'Caption','Figure caption and evidence scope.',0,0,880,52,'Caption','Muted'));
 d.make('Contents rail',1100,0,240,416,b=>{d.txt(b,'Contents label','ON THIS PAGE',0,0,230,28,'Label');d.article.sections.forEach((s,i)=>d.txt(b,'Link / '+s.id,s.short,0,52+i*40,230,30,'Navigation'));d.rect(b,'Rule',0,360,224,1);d.txt(b,'Evidence label','OWNER-REPORTED RESULT\n22 SEPTEMBER 2026',0,380,236,52,'Label','Muted');});
 d.make('Article introduction',0,440,992,300,b=>{d.txt(b,'Article title',d.article.title,0,0,940,136,'Article title');d.txt(b,'Description',d.article.description,0,152,860,100,'Intro');d.txt(b,'Period','15–22 SEPTEMBER 2026  /  PROJECT JOURNAL',0,270,940,24,'Label','Muted');});
 return Object.keys(d.c).filter(n=>n.startsWith('Article')||n.startsWith('Contents'));
};
d.figures=()=>{
 d.make('Update files',1400,0,992,228,b=>{for(const [i,name,desc]of [[0,'SP404MKII_APP0.bin','Opaque body. Role still under investigation.'],[1,'SP404MKII_APP1.bin','Readable strings and ARM instructions.']]){d.rect(b,'Row rule '+i,0,i*100,992,1);d.txt(b,'File '+i,name,0,22+i*100,450,32,'Navigation');d.txt(b,'File note '+i,desc,460,22+i*100,510,56,'Caption');}d.txt(b,'Preservation note','ORIGINALS PRESERVED  /  SHA-256 RECORDED',0,208,900,24,'Label','Muted');});
 d.make('Runtime map',1400,340,992,260,b=>{const cells=[['UPDATE FILE','Stored bytes'],['STARTUP','Copy · decompress · zero'],['RUNTIME MEMORY','Code and data in place']];cells.forEach(([label,body],i)=>{d.rect(b,'Cell '+i,i*336,0,312,172,'Surface');d.txt(b,'Cell label '+i,label,i*336+20,22,272,28,'Label');d.txt(b,'Cell text '+i,body,i*336+20,72,272,64,'Intro');});d.rect(b,'Flow line',0,202,992,1);d.txt(b,'Flow note','THE SAME BYTES NEED THE RIGHT LOCATIONS.',0,222,920,30,'Label','Muted');});
 d.make('IDA excerpt',1400,760,992,330,b=>{d.rect(b,'Code surface',0,0,992,330,'Surface');d.txt(b,'Code label','IDA / PSEUDOCODE EXCERPT',24,20,944,28,'Label','Muted');d.rect(b,'Title reference highlight',16,128,960,25,'Paper');d.txt(b,'Code',d.article.code.join('\n'),24,60,944,252,'Code');});
 d.make('Experiment scope',1400,1230,992,180,b=>{d.rect(b,'Rule',0,0,992,1);d.txt(b,'Unchanged label','KEEP',0,26,110,28,'Label','Muted');d.txt(b,'Unchanged','Stock startup, menu drawing, APP0',144,20,848,38,'Intro');d.rect(b,'Second rule',0,86,992,1);d.txt(b,'Change label','CHANGE',0,118,110,28,'Label');d.txt(b,'Change','One title in APP1',144,112,848,38,'Intro');});
 d.make('Menu title comparison',1400,1570,992,228,b=>{d.txt(b,'Before label','ORIGINAL TITLE',0,0,460,28,'Label','Muted');d.txt(b,'After label','MODIFIED TITLE',528,0,464,28,'Label','Muted');for(const [x,title,n]of [[0,'UTILITY MENU','Before'],[528,'CUSTOM MENU!','After']]){d.rect(b,'OLED '+n,x,44,464,116,'OLED black');d.txt(b,'OLED '+n+' title',title,x+24,82,416,40,'Display text','OLED pixel').fontSize='28';}d.txt(b,'Change note','12 PRINTABLE CHARACTERS  /  SAME IMAGE SIZE',0,188,950,28,'Label','Muted');});
 d.make('Menu verification',1400,1940,992,208,b=>{d.txt(b,'Columns','SYSTEM    PAD SET    EFX SET    IMPORT    BACKUP    FORMAT',150,0,832,28,'Label','Muted');for(const [row,name]of [[0,'Original'],[1,'Modified']]){d.rect(b,'Rule '+row,0,50+row*64,992,1);d.txt(b,'Row '+row,name,0,69+row*64,135,28,'Caption');for(let i=0;i<6;i++)d.txt(b,'Case '+row+' '+i,'PASS',150+i*140,69+row*64,108,28,'Label');}d.txt(b,'Scope note','CPU TESTS  /  SIX MENU SELECTIONS × TWO IMAGES',0,184,970,24,'Label','Muted');});
 d.make('Hardware observation',1400,2290,992,228,b=>{d.rect(b,'Rule',0,0,992,1);d.txt(b,'Owner quote','“it wokred”',0,28,950,70,'Article title');d.txt(b,'Attribution','OWNER REPORT / 22 SEPTEMBER 2026',0,120,950,28,'Label','Muted');d.txt(b,'Evidence scope','Reported visible success. No independent screen capture or installed-image readback.',0,166,900,60,'Caption');});
 return 'Seven linked figure mains created';
};
d.hardwareFigure=()=>{
 d.make('Menu title screen',3700,0,128,64,b=>{d.rect(b,'OLED screen background',0,0,128,64,'OLED black');const t=d.txt(b,'OLED menu title','CUSTOM MENU!',8,26,112,16,'Display text','OLED pixel');t.fontSize='12';});
 if(d.c['First change instrument'])return {id:d.c['First change instrument'].id,remaining:d.scaleQueue?.length||0};
 const b=penpot.root.children.find(s=>s.name==='First change instrument')||d.board('First change instrument',3700,260,992,626);
 const sp=b.children.find(s=>s.name==='SP instrument')||d.inst('Instrument',b,16,24,'SP instrument');
 const old=penpotUtils.findShape(s=>s.name.startsWith('OLED content slot'),sp);if(!old)throw Error('Missing OLED content slot');
 const width=old.width;old.hidden=false;old.swapComponent(d.c['Menu title screen']);old.name='Menu screen';d.scalePlan(old,width);
 d.txt(b,'Observation label','THE FIRST VISIBLE CHANGE',496,86,450,28,'Label','Muted');d.txt(b,'Observed title','CUSTOM\nMENU!',492,142,460,156,'Article title');d.txt(b,'Scope','A different title.\nThe stock instrument underneath.',496,330,448,90,'Intro');d.txt(b,'Reconstruction label','TITLE-ONLY RECONSTRUCTION\nNOT A DEVICE CAPTURE',496,472,464,52,'Label','Muted');
 const c=lib.createComponent([b]);c.name='First change instrument';c.path='OpenSP / Guide';d.c[c.name]=c;
 return {id:c.id,remaining:d.scaleQueue?.length||0};
};
d.scalePlan=(root,width)=>{const k=width/root.width,ox=root.x,oy=root.y;d.scaleQueue=d.scaleQueue||[];d.scaleQueue.push(...[root,...d.visible(root)].map(s=>({s,x:ox+(s.x-ox)*k,y:oy+(s.y-oy)*k,w:s.width*k,h:s.height*k,font:s.type==='text'?Number(s.fontSize)*k:null})));};
d.scaleBatch=()=>{for(const a of d.scaleQueue.splice(0,20)){a.s.resize(a.w,a.h);a.s.x=a.x;a.s.y=a.y;if(a.font)a.s.fontSize=String(a.font);}return {remaining:d.scaleQueue.length};};
d.section=i=>{
 const s=d.article.sections[i],n='Section / '+s.id;
 const figureNames={files:'Update files',memory:'Runtime map',code:'IDA excerpt',scope:'Experiment scope',comparison:'Menu title comparison',verification:'Menu verification',result:'Hardware observation'};
 const id=d.make(n,2600,i*1450,992,1300,b=>{let y=0;const h=d.inst('Article heading',b,0,y);d.find(h,'Heading').characters=s.title;y+=80;for(const [i,p]of s.paragraphs.entries()){const v=d.inst('Article paragraph',b,0,y,'Paragraph '+i),t=d.find(v,'Paragraph');t.characters=p;d.textFit(t,760);v.resize(760,t.height);y+=t.height+24;}const f=d.inst(figureNames[s.figure],b,0,y,'Figure');y+=f.height+16;const cap=d.inst('Figure caption',b,0,y);d.find(cap,'Caption').characters=s.caption;d.textFit(d.find(cap,'Caption'),880,'Caption');cap.resize(992,d.find(cap,'Caption').height);y+=cap.height;b.resize(992,y+8);b.setPluginData('guide-section',s.id);});
 return {i,id};
};
d.start=async(mobile,dark)=>{
 const name='First guide';let p=penpot.currentFile.pages.find(p=>p.name===name);if(!p){p=penpot.createPage();p.name=name;}await penpot.openPage(p);return {page:p.id,mobile,dark};
};
d.layout=(mobile,dark)=>{
 if(penpot.currentPage.name!=='First guide')throw Error('Open First guide');
 const name=`First change / ${mobile?'Mobile':'Desktop'} / ${dark?'Dark':'Light'}`;
 if(penpot.root.children.some(b=>b.name===name))throw Error('Board exists; inspect before resuming');
 const b=d.board(name,(dark?2040:0)+(mobile?1500:0),0,mobile?390:1440,12000,'Paper');d.active=b;d.mobile=mobile;d.isDark=dark;
 const nav=d.inst('Navigation',b,mobile?24:64,0);if(mobile){nav.resize(342,104);d.put(d.find(nav,'Wordmark'),nav,0,12);d.put(d.find(nav,'Theme selector'),nav,214,12);d.put(d.find(nav,'Primary links'),nav,76,56);d.put(d.find(nav,'Rule'),nav,0,103,342,1);}
 if(mobile){d.txt(b,'Contents mobile','ON THIS PAGE  +',24,128,342,40,'Navigation');d.rect(b,'Contents rule',24,176,342,1);}else d.inst('Contents rail',b,64,140);
 const intro=d.inst('Article introduction',b,mobile?24:384,mobile?216:136);if(mobile){intro.resize(342,354);const t=d.find(intro,'Article title');t.applyTypography(d.type['Hero mobile']);t.lineHeight='1.12';d.put(t,intro,0,0,342,164);const desc=d.find(intro,'Description');d.put(desc,intro,0,180,342,150);desc.applyTypography(d.type['Body mobile']);desc.lineHeight='1.6';const period=d.find(intro,'Period');period.characters='15–22 SEPTEMBER 2026';d.put(period,intro,0,332,342,24);}
 d.y=(mobile?216:136)+intro.height+40;
 const hero=d.inst('First change instrument',b,mobile?24:384,d.y,'First change instrument');
 if(mobile){hero.resize(342,688);const sp=d.find(hero,'SP instrument');d.put(sp,hero,21,0);d.scalePlan(sp,300);d.find(hero,'Observation label').hidden=true;d.put(d.find(hero,'Observed title'),hero,0,462,342,108);d.find(hero,'Observed title').characters='CUSTOM MENU!';d.find(hero,'Observed title').fontSize='36';d.put(d.find(hero,'Scope'),hero,0,526,342,80);d.find(hero,'Scope').applyTypography(d.type['Body mobile']);d.find(hero,'Scope').lineHeight='1.6';d.put(d.find(hero,'Reconstruction label'),hero,0,622,342,52);}
 d.y+=hero.height+(mobile?64:80);
 return {id:b.id,name,y:d.y};
};
d.placeSection=i=>{const b=d.active,m=d.mobile,s=d.article.sections[i],r=b.children.find(c=>c.name===s.title)||d.inst('Section / '+s.id,b,m?24:384,d.y,s.title);d.put(r,b,m?24:384,d.y);let y=0;const h=d.find(r,'Article heading'),t=d.find(h,'Heading');if(m){t.applyTypography(d.type['Heading mobile']);t.lineHeight='1.25';d.put(t,h,0,0,342,d.height(t.characters,342,28,1.25));h.resize(342,t.height);}d.put(h,r,0,0);y=m?h.height+24:80;for(let j=0;j<s.paragraphs.length;j++){const p=d.find(r,'Paragraph '+j),text=d.find(p,'Paragraph');d.textFit(text,m?342:760,m?'Body mobile':'Body');p.resize(m?342:760,text.height);d.put(p,r,0,y);y+=p.height+24;}const f=d.find(r,'Figure');d.put(f,r,0,y);if(m)d.mobileFigure(f,s.figure);else f.resize(992,f.component().mainInstance().height);y+=f.height+16;const cap=d.find(r,'Figure caption');d.put(cap,r,0,y);d.textFit(d.find(cap,'Caption'),m?342:880,'Caption');cap.resize(m?342:992,d.find(cap,'Caption').height);y+=cap.height;r.resize(m?342:992,y+8);d.y+=r.height+(m?64:80);return {section:s.id,y:d.y};};
d.mobileFigure=(f,kind)=>{
 if(kind==='files'){f.resize(342,302);for(let i=0;i<2;i++){d.put(d.find(f,'Row rule '+i),f,0,i*130,342,1);d.put(d.find(f,'File '+i),f,0,18+i*130,342,30);d.put(d.find(f,'File note '+i),f,0,56+i*130,342,60);}d.put(d.find(f,'Preservation note'),f,0,270,342,52);d.find(f,'Preservation note').characters='ORIGINALS PRESERVED\nSHA-256 RECORDED';}
 if(kind==='memory'){f.resize(342,446);for(let i=0;i<3;i++){d.put(d.find(f,'Cell '+i),f,0,i*128,342,112);d.put(d.find(f,'Cell label '+i),f,20,18+i*128,302,28);d.put(d.find(f,'Cell text '+i),f,20,54+i*128,302,40);}d.put(d.find(f,'Flow line'),f,0,400,342,1);const note=d.find(f,'Flow note');note.characters='THE SAME BYTES NEED\nTHE RIGHT LOCATIONS.';d.put(note,f,0,418,342,52);}
 if(kind==='code'){f.resize(342,330);d.put(d.find(f,'Code surface'),f,0,0,342,330);d.put(d.find(f,'Code label'),f,16,16,310,28);d.put(d.find(f,'Title reference highlight'),f,8,126,326,26);const text=d.find(f,'Code');text.characters='int sub_8013E8B0(...)\n{\n  // declarations omitted\n  sub_800C2558(...,\n    aUtilityMenu, -98);\n  // drawing calls omitted\n  strcpy(v4, "SYSTEM");\n  // menu entries omitted\n}';d.put(text,f,16,60,310,252);}
 if(kind==='scope'){f.resize(342,220);d.put(d.find(f,'Rule'),f,0,0,342,1);d.put(d.find(f,'Unchanged label'),f,0,20,342,28);d.put(d.find(f,'Unchanged'),f,0,56,342,60);d.put(d.find(f,'Second rule'),f,0,134,342,1);d.put(d.find(f,'Change label'),f,0,154,342,28);d.put(d.find(f,'Change'),f,0,186,342,38);}
 if(kind==='comparison'){f.resize(342,334);for(const [name,y]of [['Before',0],['After',150]]){d.put(d.find(f,name+' label'),f,0,y,342,28);d.put(d.find(f,'OLED '+name),f,0,y+38,342,96);d.put(d.find(f,'OLED '+name+' title'),f,20,y+66,302,40);d.find(f,'OLED '+name+' title').fontSize='24';}const note=d.find(f,'Change note');note.characters='12 CHARACTERS / SAME IMAGE SIZE';d.put(note,f,0,310,342,40);note.fontSize='11';}
 if(kind==='verification'){f.resize(342,234);d.find(f,'Columns').characters='SIX MENU SELECTIONS';d.put(d.find(f,'Columns'),f,0,0,342,28);for(let row=0;row<2;row++){d.put(d.find(f,'Rule '+row),f,0,44+row*76,342,1);d.put(d.find(f,'Row '+row),f,0,56+row*76,342,28);for(let i=0;i<6;i++){const a=d.find(f,'Case '+row+' '+i);a.characters='OK';d.put(a,f,i*56,86+row*76,48,24);}}const note=d.find(f,'Scope note');note.characters='CPU TESTS / NOT DEVICE TESTS';d.put(note,f,0,204,342,28);note.fontSize='11';}
 if(kind==='result'){f.resize(342,250);d.put(d.find(f,'Rule'),f,0,0,342,1);d.put(d.find(f,'Owner quote'),f,0,24,342,70);d.find(f,'Owner quote').fontSize='48';d.put(d.find(f,'Attribution'),f,0,112,342,52);d.put(d.find(f,'Evidence scope'),f,0,174,342,80);}
};
d.resume=(name,y)=>{d.active=penpot.root.children.find(b=>b.name===name);if(!d.active)throw Error('Missing board');d.mobile=name.includes('Mobile');d.isDark=name.includes('Dark');d.y=y;return {id:d.active.id,y};};
d.finish=()=>{const b=d.active,m=d.mobile;const f=b.children.find(s=>s.name==='Footer')||d.inst('Footer',b,m?24:64,d.y);d.put(f,b,m?24:64,d.y);d.find(f,'Preview note').characters='GUIDE / FIRST CHANGE';if(m){f.resize(342,106);d.put(d.find(f,'Rule'),f,0,0,342,1);d.put(d.find(f,'Project note'),f,0,24,342,48);d.find(f,'Project note').fontSize='11';d.put(d.find(f,'Preview note'),f,0,76,342,24);d.find(f,'Preview note').align='left';}b.resize(m?390:1440,d.y+f.height+32);b.setPluginData('opensp-guide',JSON.stringify({slug:'first-change',mobile:m,dark:d.isDark,linked:true}));d.queue=d.isDark?[b,...d.visible(b)]:[];return {id:b.id,width:b.width,height:b.height,darkQueue:d.queue.length};};
d.darkBatch=()=>{const map={Paper:'Dark paper',Ink:'Dark ink',Muted:'Dark muted',Line:'Dark line',Surface:'Dark surface'};for(const s of d.queue.splice(0,24)){if(s.name.startsWith('OLED'))continue;if(s.fills?.length)s.fills=s.fills.map(f=>{const name=Object.keys(map).find(n=>f.fillColorRefId===d.colors[n].id);return name?{...f,...d.colors[map[name]].asFill()}:f;});if(s.strokes?.length)s.strokes=s.strokes.map(f=>{const name=Object.keys(map).find(n=>f.strokeColorRefId===d.colors[n].id);return name?{...f,...d.colors[map[name]].asStroke(),strokeWidth:f.strokeWidth}:f;});}return {remaining:d.queue.length};};
d.cloneDark=mobile=>{const name=`First change / ${mobile?'Mobile':'Desktop'} / `;if(penpot.root.children.some(s=>s.name===name+'Dark'))throw Error('Dark board exists');const source=penpot.root.children.find(s=>s.name===name+'Light');if(!source)throw Error('Missing light board');const b=source.clone();b.name=name+'Dark';b.x=source.x+2040;b.y=source.y;d.active=b;d.mobile=mobile;d.isDark=true;d.find(b,'Theme label').characters='DARK / ●';b.setPluginData('opensp-guide',JSON.stringify({slug:'first-change',mobile,dark:true,linked:true}));d.queue=[b,...d.visible(b)];return {id:b.id,remaining:d.queue.length};};
return {loaded:true,components:Object.keys(d.c).length};
