// Shared native posters. Browser playback remains a semantic code component.
if(penpot.currentFile.id!=='24d9d841-759d-81bc-8008-b518bc70d8b3')throw Error('OpenSP only');
const lib=penpot.library.local;
const j=storage.journey={chapters:__CHAPTERS__,colors:Object.fromEntries(lib.colors.map(c=>[c.name,c])),type:Object.fromEntries(lib.typographies.map(t=>[t.name,t])),components:Object.fromEntries(lib.components.map(c=>[c.name,c]))};
j.find=(r,n)=>{const s=penpotUtils.findShape(s=>s.name===n,r)||penpotUtils.findShape(s=>s.name==='OpenSP / '+n,r);if(!s)throw Error('Missing '+n);return s;};
j.visible=r=>penpotUtils.findShapes(s=>{for(let p=s;p&&p.id!==r.id;p=p.parent)if(p.hidden||p.name.startsWith('Archive'))return false;return s.id!==r.id;},r);
j.put=(s,p,x,y,w,h)=>{if(s.parent?.id!==p.id)p.appendChild(s);if(w!==undefined)s.resize(w,h);s.x=p.x+x;s.y=p.y+y;return s;};
j.board=(name,x,y,w,h,fill)=>{const s=penpot.createBoard();s.name=name;s.resize(w,h);s.x=x;s.y=y;s.fills=fill?[j.colors[fill].asFill()]:[];return s;};
j.text=(p,name,value,x,y,w,h,style='Body',color='Ink')=>{const s=penpot.createText(value);s.name=name;s.applyTypography(j.type[style]);s.lineHeight=j.type[style].lineHeight;s.growType='fixed';s.fills=[j.colors[color].asFill()];return j.put(s,p,x,y,w,h);};
j.rect=(p,name,x,y,w,h,color='Line')=>{const s=penpot.createRectangle();s.name=name;s.fills=[j.colors[color].asFill()];s.strokes=[];return j.put(s,p,x,y,w,h);};
j.inst=(name,p,x,y,label=name)=>{const s=j.components[name].instance();s.name=label;return j.put(s,p,x,y);};
j.make=(name,x,y,w,h,draw)=>{if(j.components[name])return j.components[name];const orphan=penpot.root.children.find(s=>s.name===name);if(orphan&&(orphan.id!=='bfe8c086-048d-80e0-8008-b6e28fad9a8b'||orphan.children?.length))throw Error('Inspect unfinished component '+name);const b=orphan||j.board(name,x,y,w,h);draw(b);const c=lib.createComponent([b]);c.name=name;c.path='OpenSP / Journey';j.components[name]=c;return c;};
j.height=(value,w,size=20,leading=1.6,mono=false)=>{const cap=Math.max(1,Math.floor(w/(size*(mono?.62:.51))));let lines=0;for(const para of value.split('\n')){let used=0;for(const word of para.split(' ')){if(used&&used+word.length+1>cap){lines++;used=word.length;}else used+=(used?1:0)+word.length;}lines++;}return Math.ceil(lines*size*leading)+6;};
j.fit=(s,value,w,style='Body',size)=>{s.characters=w<=342?value.replaceAll('AntiWorkProTwerk','AntiWork\u200bProTwerk'):value;s.applyTypography(j.type[style]);s.lineHeight=j.type[style].lineHeight;if(size)s.fontSize=String(size);s.resize(w,j.height(value,w,Number(s.fontSize),Number(s.lineHeight),['Label','Navigation','Code'].includes(style)));return s;};
j.paragraph=(b,value,x,y,w,m,label='Paragraph')=>{const p=j.inst('Article paragraph',b,x,y,label);const t=j.fit(j.find(p,'Paragraph'),value,w,m?'Body mobile':'Body');j.put(t,p,0,0);p.resize(w,t.height);return p;};
j.heading=(b,value,x,y,w,m,label='Heading')=>{const h=j.inst('Article heading',b,x,y,label),t=j.fit(j.find(h,'Heading'),value,w,m?'Heading mobile':'Heading');j.put(t,h,0,0);h.resize(w,t.height);return h;};
j.timeline=(b,x,y,w,seconds)=>{const t=j.inst('Animation timeline',b,x,y);t.resize(w,44);j.put(j.find(t,'Timeline line'),t,56,21.5,w-162,1);j.put(j.find(t,'Seek handle'),t,w-112,16,12,12);j.put(j.find(t,'Playback time'),t,w-88,14,88,22);j.find(t,'Playback time').characters=`0:${String(seconds).padStart(2,'0')} / 0:${String(seconds).padStart(2,'0')}`;return t;};
j.screen=(sp,lines,r3=false)=>{const slot=penpotUtils.findShape(s=>s.name==='Journey screen slot'||s.name==='Menu screen'||s.name.startsWith('OLED content slot'),sp);if(!slot)throw Error('Screen slot missing');const x=slot.x,y=slot.y,w=slot.width,h=slot.height;slot.swapComponent(j.components[r3?'AntiWorkProTwerk R3':'Journey screen']);slot.name='Journey screen slot';const k=w/128;const children=j.visible(slot).map(s=>({s,x:s.x-slot.x,y:s.y-slot.y,w:s.width,h:s.height,font:s.type==='text'?Number(s.fontSize):null}));slot.resize(w,h);slot.x=x;slot.y=y;for(const c of children){c.s.resize(c.w*k,c.h*k);c.s.x=x+c.x*k;c.s.y=y+c.y*k;if(c.font)c.s.fontSize=String(c.font*k);}if(!r3){const names=['Journey title','Journey line 1','Journey line 2','Journey footer'];names.forEach((name,i)=>{const t=j.find(slot,name);t.characters=lines[i];t.fontSize=String((i===3?7:8)*k);j.put(t,slot,8*k,(7+i*13)*k,112*k,12*k);});}return slot;};
j.captureMobile=()=>{if(penpot.currentPage.name!=='First guide')throw Error('Open First guide, then retry');const mobile=penpot.root.children.find(s=>s.name==='First change / Mobile / Light');if(!mobile)throw Error('Missing first-guide mobile source');const sp=j.find(mobile,'SP instrument');j.mobileSP={id:sp.id,width:sp.width};return j.mobileSP;};
j.mobileInstrument=()=>{const sp=j.components.Instrument.instance(),k=j.mobileSP.width/sp.width,x=sp.x,y=sp.y;const shapes=[sp,...j.visible(sp)].map(s=>({s,x:s.x-x,y:s.y-y,w:s.width,h:s.height,font:s.type==='text'?Number(s.fontSize):null}));for(const c of shapes){c.s.resize(c.w*k,c.h*k);c.s.x=x+c.x*k;c.s.y=y+c.y*k;if(c.font)c.s.fontSize=String(c.font*k);}return sp;};
j.prepare=()=>{
 if(penpot.currentPage.name!=='Guide components')throw Error('Open Guide components, then retry');
 if(!j.mobileSP)throw Error('Capture the existing mobile Instrument first');
 j.make('Journey screen',7600,0,128,64,b=>{j.rect(b,'OLED screen background',0,0,128,64,'OLED black');['Journey title','Journey line 1','Journey line 2','Journey footer'].forEach((n,i)=>{const t=j.text(b,n,['PROJECT RECORD','TEST / OBSERVE','CHECK THE RESULT','SCHEMATIC'][i],8,7+i*13,112,12,'Display text','OLED pixel');t.fontSize=i===3?'7':'8';});});
 for(const m of [false,true])j.make(m?'Journey sequence mobile':'Journey sequence',7600+(m?1100:0),160,m?342:992,m?890:650,b=>{const sp=m?j.mobileInstrument():j.components.Instrument.instance();sp.name='SP instrument';j.put(sp,b,m?21:16,m?0:24);j.screen(sp,['PROJECT RECORD','TEST / OBSERVE','CHECK THE RESULT','SCHEMATIC']);j.text(b,'Stage title','Check the result',m?0:496,m?470:112,m?342:448,96,m?'Heading mobile':'Heading');j.text(b,'Stage explanation','Compare the test with the observed result. Keep the remaining uncertainty visible.',m?0:496,m?582:224,m?342:448,144,m?'Body mobile':'Body');j.timeline(b,m?0:496,m?742:400,m?342:448,12);j.text(b,'Stage scope','Schematic sequence. No device connection.',m?0:496,m?802:468,m?342:448,72,'Caption','Muted');});
 j.make('Journey contents',9200,0,240,600,b=>{j.text(b,'Contents heading','ON THIS PAGE',0,0,240,28,'Label');for(let i=0;i<8;i++)j.text(b,'Contents link '+i,'Section '+(i+1),0,52+i*44,240,38,'Navigation');j.rect(b,'Rule',0,424,240,1);j.text(b,'Evidence label','PROJECT RECORD',0,448,240,124,'Label','Muted');});
 j.make('Journey navigation',9200,760,992,164,b=>{j.rect(b,'Rule',0,0,992,1);j.text(b,'Previous label','PREVIOUS',0,24,450,28,'Label','Muted');j.text(b,'Previous title','Previous chapter',0,64,450,84,'Intro');j.text(b,'Next label','NEXT',528,24,464,28,'Label','Muted');j.text(b,'Next title','Next chapter',528,64,464,84,'Intro');});
 for(const name of ['Journey sequence','Journey sequence mobile']){const b=j.components[name].mainInstance(),m=name.endsWith('mobile');if(!b.children.some(s=>s.name==='Timeline title'))j.text(b,'Timeline title','Follow the experiment',m?0:496,m?460:72,m?342:448,80,'Heading');if(!b.children.some(s=>s.name==='Step counter'))j.text(b,'Step counter','04 / 04',m?0:496,m?556:168,m?342:448,24,'Label','Muted');}
 j.layoutMains();
 return {components:Object.values(j.components).filter(c=>c.path==='OpenSP / Journey').map(c=>({id:c.id,name:c.name}))};
};
j.layoutMains=()=>{if(penpot.currentPage.name!=='Guide components')throw Error('Open Guide components');for(const m of [false,true]){const b=j.components[m?'Journey sequence mobile':'Journey sequence'].mainInstance(),x=m?0:496,w=m?342:448;let y=m?460:72;for(const [name,size,leading,after]of [['Timeline title',28,1.25,28],['Step counter',13,1.54,12],['Stage title',22,1.4,16],['Stage explanation',18,1.6,16]]){const t=j.find(b,name);t.fontSize=String(size);t.lineHeight=String(leading);const h=j.height(t.characters,w,size,leading,name==='Step counter');j.put(t,b,x,y,w,h);y+=h+after;}j.put(j.find(b,'Animation timeline'),b,x,y);y=Math.max(y+68,m?0:620);const t=j.find(b,'Stage scope');t.fontSize='14';t.lineHeight='1.6';j.put(t,b,0,y,m?342:760,j.height(t.characters,m?342:760,14,1.6));b.resize(m?342:992,y+t.height+24);}return {updated:['Journey sequence','Journey sequence mobile']};};
j.openIndex=async()=>{let p=penpot.currentFile.pages.find(p=>p.name==='Guide index');if(!p){p=penpot.createPage();p.name='Guide index';}await penpot.openPage(p);return {page:p.id};};
j.indexLayout=m=>{if(penpot.currentPage.name!=='Guide index')throw Error('Open Guide index');if(!j.indexCopy||!j.first)throw Error('Load shared index copy');const name=`Guide index / ${m?'Mobile':'Desktop'} / Light`;if(penpot.root.children.some(b=>b.name===name))throw Error('Index board exists; inspect before resuming');const b=j.board(name,m?1500:0,0,m?390:1440,7000,'Paper'),x=m?24:384,w=m?342:992,pw=m?342:760;const nav=j.inst('Navigation',b,m?24:64,0);if(m){nav.resize(342,104);j.put(j.find(nav,'Wordmark'),nav,0,12);j.put(j.find(nav,'Theme selector'),nav,214,12);j.put(j.find(nav,'Primary links'),nav,76,56);j.put(j.find(nav,'Rule'),nav,0,103,342,1);}else{j.text(b,'Index home link','Back to OpenSP',64,140,240,32,'Navigation');j.text(b,'Index rail',j.indexCopy.rail,64,192,240,80,'Label','Muted');}const intro=j.inst('Article introduction',b,x,m?144:136),title=j.fit(j.find(intro,'Article title'),j.indexCopy.title,pw,m?'Hero mobile':'Article title');j.put(title,intro,0,0);const desc=j.fit(j.find(intro,'Description'),j.indexCopy.description,pw,m?'Body mobile':'Intro');j.put(desc,intro,0,title.height+24);j.find(intro,'Period').hidden=true;intro.resize(w,title.height+desc.height+24);let y=(m?144:136)+intro.height+48;const entries=[j.first,...j.chapters];for(const [i,entry]of entries.entries()){const row=j.inst('Guide row',b,x,y,'Guide / '+(entry.slug||'first-change')),column=m?48:56,inner=w-column-40;j.put(j.find(row,'Rule'),row,0,0,w,1);j.find(row,'Index').characters=String(i+1).padStart(2,'0');j.put(j.find(row,'Index'),row,0,24,m?32:40,28);const title=j.fit(j.find(row,'Title'),entry.title,inner,'Intro');j.put(title,row,column,20);const desc=j.fit(j.find(row,'Description'),entry.description,inner,'Caption');j.put(desc,row,column,28+title.height);const arrow=j.find(row,'Link arrow');j.put(arrow,row,w-28,22,28,30);row.resize(w,title.height+desc.height+52);y+=row.height;}y+=32;const note=j.paragraph(b,j.indexCopy.note,x,y,pw,m,'Index scope');const nt=j.find(note,'Paragraph');nt.fontSize='16';nt.lineHeight='1.6';nt.resize(pw,j.height(j.indexCopy.note,pw,16,1.6));note.resize(pw,nt.height);y+=note.height+64;const footer=j.inst('Footer',b,m?24:64,y);j.find(footer,'Preview note').characters='GUIDES';if(m){footer.resize(342,106);j.put(j.find(footer,'Rule'),footer,0,0,342,1);j.put(j.find(footer,'Project note'),footer,0,24,342,48);j.find(footer,'Project note').fontSize='11';j.put(j.find(footer,'Preview note'),footer,0,76,342,24);j.find(footer,'Preview note').align='left';}b.resize(b.width,y+footer.height+32);b.setPluginData('opensp-guide-index',JSON.stringify({mobile:m,dark:false,source:'src/content/guide-index.json'}));j.active=b;j.mobile=m;return {id:b.id,mobile:m,height:b.height,rows:entries.length};};
j.indexDark=()=>{const b=j.active.clone();b.name=j.active.name.replace(/Light$/,'Dark');b.x=j.active.x+2040;j.find(b,'Theme label').characters='DARK / ●';b.setPluginData('opensp-guide-index',JSON.stringify({mobile:j.mobile,dark:true,source:'src/content/guide-index.json'}));j.darkQueue=[b,...j.visible(b)];return {id:b.id,remaining:j.darkQueue.length};};
j.open=async()=>{let p=penpot.currentFile.pages.find(p=>p.name==='Guide series');if(!p){p=penpot.createPage();p.name='Guide series';}await penpot.openPage(p);return {page:p.id,boards:penpot.root.children.length};};
j.begin=(slug,mobile)=>{
 if(penpot.currentPage.name!=='Guide series')throw Error('Open Guide series');
 const a=j.chapters.find(a=>a.slug===slug);if(!a)throw Error('Unknown chapter');const index=j.chapters.indexOf(a);const name=`${String(index+2).padStart(2,'0')} / ${a.title} / ${mobile?'Mobile':'Desktop'} / Light`;
 if(penpot.root.children.some(s=>s.name===name))throw Error('Board exists; resume explicitly');
 // Fixed row pitch gives each long mobile article its own strip without overlap.
 const b=j.board(name,mobile?1500:0,index*20000,mobile?390:1440,18000,'Paper');j.active=b;j.article=a;j.mobile=mobile;
 b.setPluginData('opensp-journey',JSON.stringify({slug,mobile,dark:false,source:'src/content/journey/'+slug+'.json'}));
 const nav=j.inst('Navigation',b,mobile?24:64,0);if(mobile){nav.resize(342,104);j.put(j.find(nav,'Wordmark'),nav,0,12);j.put(j.find(nav,'Theme selector'),nav,214,12);j.put(j.find(nav,'Primary links'),nav,76,56);j.put(j.find(nav,'Rule'),nav,0,103,342,1);}
 const x=mobile?24:384,w=mobile?342:992,pw=mobile?342:760;
 if(mobile){j.text(b,'Mobile contents','ON THIS PAGE  +',24,128,342,28,'Navigation');j.rect(b,'Contents rule',24,176,342,1);}else{const rail=j.inst('Journey contents',b,64,140);const labels=[...a.sections.map(s=>s.short),'Offline exercise','Evidence'];for(let i=0;i<8;i++){const s=j.find(rail,'Contents link '+i);s.hidden=i>=labels.length;if(labels[i])s.characters=labels[i];}j.fit(j.find(rail,'Evidence label'),a.evidenceLabel+'\n'+a.period,240,'Label');}
 const intro=j.inst('Article introduction',b,x,mobile?216:136),title=j.fit(j.find(intro,'Article title'),a.title,mobile?342:760,mobile?'Hero mobile':'Article title');j.put(title,intro,0,0);let y=title.height+24;const desc=j.fit(j.find(intro,'Description'),a.description,pw,mobile?'Body mobile':'Intro');j.put(desc,intro,0,y);y+=desc.height+24;const period=j.fit(j.find(intro,'Period'),a.period+' / '+a.category,pw,'Label');j.put(period,intro,0,y);intro.resize(w,y+period.height);j.y=(mobile?216:136)+intro.height+40;
 const summary=j.paragraph(b,a.summary,x,j.y,pw,mobile,'Chapter summary');j.y+=summary.height+40;
 const hero=j.inst(mobile?'Journey sequence mobile':'Journey sequence',b,x,j.y,'Journey sequence');const final=a.timeline.steps.at(-1);j.screen(j.find(hero,'SP instrument'),final.display,a.timeline.kind==='r3');j.fit(j.find(hero,'Stage title'),final.title,mobile?342:448,mobile?'Heading mobile':'Heading');j.fit(j.find(hero,'Stage explanation'),final.body,mobile?342:448,mobile?'Body mobile':'Body');j.fit(j.find(hero,'Stage scope'),a.timeline.caption,mobile?342:448,'Caption');const clock=j.find(hero,'Playback time');const sec=Math.round(a.timeline.duration/1000);clock.characters=`0:${String(sec).padStart(2,'0')} / 0:${String(sec).padStart(2,'0')}`;
 // Stage rows reserve room for the longest chapter-specific state.
 let ty=mobile?470:96;for(const [field,values,style]of [['Stage title',a.timeline.steps.map(s=>s.title),mobile?'Heading mobile':'Heading'],['Stage explanation',a.timeline.steps.map(s=>s.body),mobile?'Body mobile':'Body']]){const t=j.find(hero,field),h=Math.max(...values.map(v=>j.height(v,mobile?342:448,Number(j.type[style].fontSize),Number(j.type[style].lineHeight))));j.put(t,hero,mobile?0:496,ty,mobile?342:448,h);ty+=h+24;}
 const timeline=j.find(hero,'Animation timeline');j.put(timeline,hero,mobile?0:496,ty);ty+=68;const cap=j.find(hero,'Stage scope');j.put(cap,hero,mobile?0:496,ty);hero.resize(w,Math.max(mobile?0:620,ty+cap.height+24));j.y+=hero.height+32;
 j.text(b,'Sequence disclosure','READ ALL '+a.timeline.steps.length+' STEPS  +',x,j.y,pw,28,'Navigation');j.y+=mobile?92:108;
 return {id:b.id,slug,mobile,y:j.y};
};
j.section=i=>{const a=j.article,s=a.sections[i],m=j.mobile,b=j.active,x=m?24:384,w=m?342:760;const h=j.heading(b,s.title,x,j.y,w,m,'Section heading / '+s.id);j.y+=h.height+24;for(const [n,value]of s.paragraphs.entries()){const p=j.paragraph(b,value,x,j.y,w,m,`${s.id} / paragraph ${n}`);j.y+=p.height+24;}if(s.steps){const p=j.paragraph(b,s.steps.map((step,n)=>`${n+1}. ${step}`).join('\n\n'),x,j.y,w,m,s.id+' / reasoning');j.y+=p.height+24;}if(s.checkpoint){const p=j.paragraph(b,s.checkpoint,x,j.y,w,m,s.id+' / checkpoint');j.y+=p.height+24;}j.y+=m?40:56;return {section:s.id,y:j.y};};
j.finish=()=>{const a=j.article,m=j.mobile,b=j.active,x=m?24:384,w=m?342:760,wide=m?342:992;let y=j.y;
 const h=j.heading(b,a.exercise.title,x,y,w,m,'Offline exercise heading');y+=h.height+24;const intro=j.paragraph(b,a.exercise.intro,x,y,w,m,'Offline exercise introduction');y+=intro.height+24;
 const cp=j.inst('Reader checkpoint',b,x,y,'Offline exercise');j.put(j.find(cp,'Rule'),cp,0,0,w,1);j.find(cp,'Checkpoint heading').characters='Python example +';j.put(j.find(cp,'Checkpoint heading'),cp,0,24,w,40);j.find(cp,'Steps').hidden=true;const result=j.fit(j.find(cp,'Command'),a.exercise.expected,w,'Code',m?12:14);j.put(result,cp,0,92);const download=j.find(cp,'Download');download.characters='Download the offline Python example';j.put(download,cp,0,92+result.height+24,w,30);const note=j.fit(j.find(cp,'Checkpoint note'),a.exercise.explanation,w,'Caption');j.put(note,cp,0,92+result.height+76);cp.resize(w,92+result.height+76+note.height);y+=cp.height+80;
 const ev=j.inst('Evidence footer',b,x,y,'Chapter evidence');j.put(j.find(ev,'Rule'),ev,0,0,wide,1);j.put(j.find(ev,'Evidence heading'),ev,0,32,w,56);j.find(ev,'Evidence heading').characters='The record behind this chapter';const et=j.fit(j.find(ev,'Evidence text'),a.evidenceLabel+'. Read the curated evidence record for the retained sources and limits.',w,m?'Body mobile':'Body');j.put(et,ev,0,112);j.find(ev,'Build disclosure').characters='Evidence limits +';j.put(j.find(ev,'Build disclosure'),ev,0,136+et.height,w,36);j.find(ev,'References').hidden=true;j.find(ev,'Return link').characters='All guides';j.put(j.find(ev,'Return link'),ev,0,200+et.height,w,30);ev.resize(wide,248+et.height);y+=ev.height+48;
 const n=j.inst('Journey navigation',b,x,y);n.resize(wide,m?272:200);j.put(j.find(n,'Rule'),n,0,0,wide,1);const index=j.chapters.indexOf(a),prev=index?j.chapters[index-1].title:'Our first change on the SP.',next=j.chapters[index+1]?.title||'All guides';for(const [prefix,value,xx,yy]of [['Previous',prev,0,0],['Next',next,m?0:528,m?136:0]]){j.put(j.find(n,prefix+' label'),n,xx,yy+24,m?342:464,28);const t=j.fit(j.find(n,prefix+' title'),value,m?342:464,'Intro',m?22:24);j.put(t,n,xx,yy+64);}y+=n.height+64;
 const footer=j.inst('Footer',b,m?24:64,y);if(m){footer.resize(342,106);j.put(j.find(footer,'Rule'),footer,0,0,342,1);j.put(j.find(footer,'Project note'),footer,0,24,342,48);j.find(footer,'Project note').fontSize='11';j.put(j.find(footer,'Preview note'),footer,0,76,342,24);j.find(footer,'Preview note').align='left';}j.find(footer,'Preview note').characters='GUIDE / '+a.category.toUpperCase();b.resize(m?390:1440,y+footer.height+32);if(b.height>19600)throw Error('Chapter row exceeds reserved pitch');return {id:b.id,slug:a.slug,mobile:m,height:b.height};};
j.dark=()=>{const source=j.active,b=source.clone();b.name=source.name.replace(/Light$/,'Dark');b.x=source.x+2040;b.y=source.y;j.find(b,'Theme label').characters='DARK / ●';b.setPluginData('opensp-journey',JSON.stringify({slug:j.article.slug,mobile:j.mobile,dark:true,source:'src/content/journey/'+j.article.slug+'.json'}));j.darkQueue=[b,...j.visible(b)];return {id:b.id,remaining:j.darkQueue.length};};
j.darkBatch=()=>{const map={Paper:'Dark paper',Ink:'Dark ink',Muted:'Dark muted',Line:'Dark line',Surface:'Dark surface'};for(const s of j.darkQueue.splice(0,80)){if(s.fills?.length)s.fills=s.fills.map(f=>{const name=Object.keys(map).find(n=>f.fillColorRefId===j.colors[n].id);return name?{...f,...j.colors[map[name]].asFill()}:f;});if(s.strokes?.length)s.strokes=s.strokes.map(f=>{const name=Object.keys(map).find(n=>f.strokeColorRefId===j.colors[n].id);return name?{...f,...j.colors[map[name]].asStroke(),strokeWidth:f.strokeWidth}:f;});}return {remaining:j.darkQueue.length};};
// Keep the native poster's reading order aligned with JourneyTimeline.astro.
const begin=j.begin;
j.begin=(slug,m)=>{begin(slug,m);const b=j.active,a=j.article,hero=j.find(b,'Journey sequence'),summary=j.find(b,'Chapter summary'),x=m?24:384,w=m?342:992,pw=m?342:760;const top=summary.y-b.y;j.put(hero,b,x,top);let y=m?460:72;const title=j.fit(j.find(hero,'Timeline title'),a.timeline.title,m?342:448,'Heading',28);j.put(title,hero,m?0:496,y);y+=title.height+28;const count=j.find(hero,'Step counter');count.characters=String(a.timeline.steps.length).padStart(2,'0')+' / '+String(a.timeline.steps.length).padStart(2,'0');j.put(count,hero,m?0:496,y,m?342:448,24);y+=36;for(const [field,values,size,leading]of [['Stage title',a.timeline.steps.map(s=>s.title),22,1.4],['Stage explanation',a.timeline.steps.map(s=>s.body),18,1.6]]){const t=j.find(hero,field),h=Math.max(...values.map(v=>j.height(v,m?342:448,size,leading)));t.fontSize=String(size);t.lineHeight=String(leading);j.put(t,hero,m?0:496,y,m?342:448,h);y+=h+16;}j.put(j.find(hero,'Animation timeline'),hero,m?0:496,y);y=Math.max(y+68,m?0:620);const caption=j.fit(j.find(hero,'Stage scope'),a.timeline.caption+(a.timeline.kind==='r3'?'':' Illustrative timing; no device connection.'),pw,'Caption',14);caption.lineHeight='1.6';j.put(caption,hero,0,y);hero.resize(w,y+caption.height);const disclosure=j.find(b,'Sequence disclosure');disclosure.characters='READ EVERY STEP  +';j.put(disclosure,b,x,top+hero.height+16,pw,40);j.put(summary,b,x,top+hero.height+88);j.y=top+hero.height+88+summary.height+(m?48:64);return {id:b.id,slug,mobile:m,y:j.y};};
const finish=j.finish;
j.finishEvidence=()=>{const b=j.active,a=j.article,m=j.mobile,w=m?342:760,ev=j.find(b,'Chapter evidence'),oldHeight=ev.height;j.find(ev,'Evidence heading').characters='Evidence and limits';const copy=[a.evidenceLabel+'. The reports below are retained project records; their underlying files are not published here. Read the curated evidence record.',...a.limits].join('\n\n');const t=j.fit(j.find(ev,'Evidence text'),copy,w,m?'Body mobile':'Body');j.put(t,ev,0,112);j.find(ev,'Build disclosure').hidden=true;j.find(ev,'Return link').hidden=true;const y=112+t.height+24,disclosure=j.find(ev,'References');disclosure.hidden=false;disclosure.characters='Source reports +';j.put(disclosure,ev,0,y+12,w,40);ev.resize(m?342:992,y+72);const delta=ev.height-oldHeight;j.find(b,'Journey navigation').y+=delta;j.find(b,'Footer').y+=delta;b.resize(b.width,b.height+delta);if(b.height>19600)throw Error('Chapter row exceeds reserved pitch');return {id:b.id,slug:a.slug,mobile:m,height:b.height};};
j.finish=()=>{finish();return j.finishEvidence();};
return {loaded:j.chapters.length};
