if(penpot.currentPage.name!=='SP components')throw new Error('Open SP components first');
const ds=storage.ds, lib=penpot.library.local;
const sp=Object.fromEntries(lib.components.filter(c=>c.path==='SP').map(c=>[c.name,c]));ds.sp=sp;
function rebuild(name,draw){const b=sp[name].mainInstance();if(b.getPluginData('native-migrated'))throw new Error(name+' already migrated');for(const child of b.children){child.hidden=true;child.name='Archived SVG source (hidden)';}b.fills=[];draw(b);b.setPluginData('native-migrated','2026-09-28');}
ds.fit=(s,w,h)=>{const ow=s.width,oh=s.height;const children=penpotUtils.findShapes(v=>!v.hidden,s).map(v=>({s:v,x:(v.x-s.x)/ow,y:(v.y-s.y)/oh,w:v.width/ow,h:v.height/oh,font:v.type==='text'?Number(v.fontSize):null}));s.resize(w,h);for(const a of children){if(a.s.children?.length)continue;a.s.resize(a.w*w,a.h*h);a.s.x=s.x+a.x*w;a.s.y=s.y+a.y*h;if(a.font)a.s.fontSize=String(a.font*w/ow);}return s;};
rebuild('Pad - idle',b=>{ds.rect(b,'Pad face',0,0,46,39,'Paper','Ink',1.2);ds.text(b,'Pad number','1',29,4,14,14,'Pad number','Ink','center');});
rebuild('Pad - active',b=>{const s=ds.instance(sp['Pad - idle'],b,0,0,'Pad base');penpotUtils.findShape(s=>s.name==='Pad face',s).fills=ds.fill('Ink');penpotUtils.findShape(s=>s.name==='Pad number',s).fills=ds.fill('Paper');});
rebuild('Button',b=>{ds.rect(b,'Button face',0,0,46,39,'Paper','Ink',1);ds.text(b,'Button label','HOLD',3,14,40,20,'Micro','Ink','center');});
rebuild('Knob',b=>{ds.text(b,'Knob label','CTRL 1',0,0,44,10,'Micro','Ink','center');ds.ellipse(b,'Knob body',2,12,40,40,'Paper','Ink',1.4);ds.path(b,'Knob indicator','M22 32 L13 19',null,'Ink',2);});
rebuild('Display',b=>{ds.ellipse(b,'Circular bezel',1,1,130,130,'Paper','Ink',1.5);ds.rect(b,'OLED background',11,38,110,62,'Ink');ds.text(b,'OLED heading','OPENSP',14,45,104,9,'Micro','Paper','center',6);ds.text(b,'OLED value','HELLO, SP.',17,63,100,19,'Display text','Paper');ds.path(b,'OLED waveform','M17 87 L29 87 L34 80 L39 94 L44 83 L49 87 L115 87',null,'Paper');});
rebuild('Enclosure',b=>{ds.rect(b,'Outer enclosure',1,1,364,570,'Paper','Ink',1.6);ds.rect(b,'Inset panel',10,18,346,536,'Paper','Ink',.7);ds.text(b,'OpenSP marking','OPENSP',42,22,78,16,'Pad number','Ink','center');ds.text(b,'Model marking','SP-404MKII',210,22,112,16,'Pad number','Ink','center');for(const x of [34,333])for(const y of [32,542])ds.ellipse(b,'Case screw',x-4,y-4,8,8,'Paper','Ink',.8);});
rebuild('Pad grid',b=>{for(let i=0;i<16;i++){const s=ds.instance(sp['Pad - idle'],b,1+(i%4)*58,1+Math.floor(i/4)*50,'Pad '+(i+1));ds.override(s,'Pad number',String(i+1));}});
rebuild('Performance buttons',b=>{for(const [i,label] of ['BUS FX','HOLD','EXT\nSOURCE','SUB PAD'].entries()){const s=ds.instance(sp.Button,b,1,1+i*50,label.replace('\n',' '));ds.override(s,'Button label',label);if(label.includes('\n'))penpotUtils.findShape(v=>v.name==='Button label',s).y=s.y+10;}});
rebuild('Effect buttons',b=>{for(const [side,x,labels] of [['left',1,['FILTER +\nDRIVE','RESONATOR','DELAY']],['right',212,['ISOLATOR','DJFX\nLOOPER','MFX']]])for(let i=0;i<3;i++){const y=1+i*35,dir=side==='left'?1:-1,top=dir*(i===0?10:0),bottom=dir*(i===2?10:0);const p=ds.path(b,labels[i].replace('\n',' ')+' face',`M${x+top} ${y} L${x+43+top} ${y} L${x+43+bottom} ${y+28} L${x+bottom} ${y+28} Z`,'Paper','Ink');ds.text(b,labels[i].replace('\n',' ')+' label',labels[i],x+(top+bottom)/2,y+(labels[i].includes('\n')?6:10),43,20,'Micro','Ink','center',6);}});
function button(b,label,x,y,w,h,size){const s=ds.instance(sp.Button,b,x,y,label.replaceAll('\n',' '));ds.fit(s,w,h);ds.override(s,'Button label',label);const t=penpotUtils.findShape(v=>v.name==='Button label',s);t.resize(w-2,h-2);t.x=s.x+1;t.y=s.y+(label.includes('\n')?3:Math.max(2,(h-size*1.2)/2));t.fontSize=String(size);return s;}
rebuild('Control section',b=>{const rows=[['PATTERN\nSELECT','PATTERN\nEDIT','RECORD\nSETTING'],['DEL','REC','RESAMPLE'],['EXIT','COPY','REMAIN']];rows.forEach((row,r)=>row.forEach((label,c)=>button(b,label,1+c*38,19+r*33,29,21,4.8)));['START /\nEND','PITCH /\nSPEED','MARK'].forEach((label,i)=>button(b,label,125+i*38,19,28,21,4.8));const k=ds.instance(sp.Knob,b,249,-1,'VALUE knob');ds.fit(k,28,36);ds.override(k,'Knob label','VALUE');['BPM\nSYNC','GATE','LOOP','REVERSE','ROLL'].forEach((label,i)=>button(b,label,117+i*32,52,26,20,4.6));['A/F','B/G','C/H','D/I','E/J','SHIFT'].forEach((label,i)=>button(b,label,117+i*28,85,21,19,5));});
rebuild('Instrument',b=>{ds.instance(sp.Enclosure,b,17,-1,'Enclosure');for(const [i,label]of ['VOLUME','CTRL 1','CTRL 2','CTRL 3'].entries()){const k=ds.instance(sp.Knob,b,61+i*78,36,label+' knob');ds.override(k,'Knob label',label);}for(const [name,x,y] of [['Display',134,101],['Effect buttons',72,120],['Control section',60,229],['Pad grid',60,346],['Performance buttons',292,346]])ds.instance(sp[name],b,x,y,name);});
return {migrated:Object.keys(sp),instrumentNested:sp.Instrument.mainInstance().children.filter(s=>!s.hidden).map(s=>({name:s.name,component:s.component()?.name}))};
